apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-gitops-cp-cp4ba-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/gitops-cp-cp4ba-operator/namespace
    repoURL: https://github.com/vivek-cp4ba/cp4ba-repo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
