apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: ibm-dba-odm-db-secret
  namespace: {{ .Values.odmdbsecret.namespace }}
type: Opaque
stringData:
  db-user: {{ .Values.odmdbsecret.db_user }}
  db-password: {{ .Values.odmdbsecret.db_password }}